module TrailblazeSpeedUp
  BASE_FRAME_RATE = 40
  DEFAULT_TURBO_MULTIPLIER = 2.0
  DEFAULT_FRAMESKIP = 0

  TURBO_MULTIPLIERS = [
    1.5,
    2.0,
    4.0,
  ]

  OPTIONS_ORDER_FRAMESKIP = 25
  OPTIONS_ORDER_TURBO_SPEED = 26
end
